---
fpu:
  num_f_regs : 32  #Number of registers in the FPU register file
  extensions:
    # - ZFINX
    # - ZFMin


xif:
  XLEN: 32
  FLEN: 32
  X_NUM_RS: 3       #Number of register file read ports that can be used by the eXtension interface
  X_ID_WIDTH: 4     #Width of ID field.
  X_MEM_WIDTH:  32  #Memory access width for loads/stores via the eXtension interface
  X_RFR_WIDTH:  32  #Register file read access width for the eXtension interface
  X_RFW_WIDTH:  32  #Register file write access width for the eXtension interface
  X_MISA:  0        #MISA extensions implemented on the eXtension interface
  X_ECS_XS:  0      #Default value for mstatus.XS

fpu_pipeline:
  num_pipeline_stages: 4 #Number of stages in the FPU pipeline
  queue_depth: 4 #Depth of the FPU instruction queue - set to 0 to disable

  OOO: false #Out of order execution - Not yet implemented
  forwarding: false #Forward/bypass result to next operation - Not yet implemented
  steps:  #step 0 is the last step in the pipeline
    execute_step: 2
    memory_step: 1
    writeback_step: 0

execute_cycles: #Number of cycles for execution of each instruction
  default: 1
  FADD: 4
  FSQRT: 19
  FDIV: 16