---
fpu:
  num_f_regs : 32  #Number of registers in the FPU register file
  # extensions:
    # - ZFINX
    # - ZFMin
    # - RV64 #Required for RV64. Also update XLEN and X_RFR/X_RFW to 64
    # - EXT_D #Update FLEN and Mem width accordingly to 64

xif:
  XLEN: 32          #Width of integer registers. - Set to 64 for RV64
  FLEN: 32          #Width of floating point registers.
  X_NUM_RS: 3       #Number of register file read ports that can be used by the eXtension interface
  X_ID_WIDTH: 4     #Width of ID field.
  X_MEM_WIDTH:  32  #Memory access width for loads/stores via the eXtension interface
  X_RFR_WIDTH:  32  #Register file read access width for the eXtension interface - Set to 64 for RV64
  X_RFW_WIDTH:  32  #Register file write access width for the eXtension interface - Set to 64 for RV64
  X_MISA:  0        #MISA extensions implemented on the eXtension interface
  X_ECS_XS:  0      #Default value for mstatus.XS

fpu_pipeline:
  num_pipeline_stages: 3 #Number of stages in the FPU pipeline
  queue_depth: 2 #Depth of the FPU instruction queue - set to 0 to disable
  steps:  #step 0 is the final step in the pipeline
    execute_step: 2
    memory_step: 1
    writeback_step: 0
  hazards: #Hazards the controller will check
    - RAW
    # - WAR - Not implemted as OOO is not implemented - Thought to be handled by CPU
    # - WAW - Not implemted as OOO is not implemented - Thought to be handled by CPU
  OOO: false #Out of order execution - Not yet implemented  - Thought to be handled by CPU
  forwarding: true #Forward/bypass result to next operation

execute_cycles: #Number of cycles for execution of each instruction
  default: 1
  FSQRT: 19
  FDIV: 16

defines: #Will be added as defines
  - RF_RESET_VALUE 0.0f #Reset value for the register file. NAN used if not specified
  - FCSR_RM_RESET_VALUE 0b000 #Rounding mode set on reset. 0 (RNE) used by default
  - queue_fallthrough #Operate queue in fallthrough mode
  # - NO_ROUNDING #Use cpp default rounding mode
  # - TESTFLOAT

constInts: #Will be added as constInts
  #...