---
fpu:
  extensions:
  #  - ZFINX #Remember to update Mabi and ARCH in common.mk

fpu_pipeline:
  num_pipeline_stages: 2 #Number of stages in the FPU pipeline
  queue_depth: 0 #Depth of the FPU instruction queue
  steps:  #step 0 is the last step in the pipeline
    execute_step: 0
    memory_step: 0
    writeback_step: 0
  forwarding: true

execute_cycles:
  default: 1
  FDIV: 11
  FSQRT: 11