---

fpu_pipeline:
  num_pipeline_stages: 1 #Number of stages in the FPU pipeline
  queue_depth: 1 #Depth of the FPU instruction queue
  steps:  #step 0 is the last step in the pipeline
    execute_step: 0
    memory_step: 0
    writeback_step: 0

execute_cycles:
  default: 1

defines: #Will be added as defines
  - RF_RESET_VALUE 00.00