---
fpu:
  extensions:
    - RV64

xif:
  XLEN: 64
  X_RFR_WIDTH: 64
  X_RFW_WIDTH: 64

fpu_pipeline:
  num_pipeline_stages: 1 #Number of stages in the FPU pipeline
  queue_depth: 0 #Depth of the FPU instruction queue
  steps:  #step 0 is the last step in the pipeline
    execute_step: 0
    memory_step: 0
    writeback_step: 0

execute_cycles:
  default: 0
  FDIV: 0
  FSQRT: 0

defines:
  - TESTFLOAT